#! /bin/bash
f=$1  
shift  
cmd=$*  
tmpf="`mktemp /tmp/onchange.XXXXX`"  
cp "$f" "$tmpf"  
trap "rm $tmpf; exit 1" 2
while : ; do 
    if [ "$f" -nt "$tmpf" ]; then  
        cp "$f" "$tmpf"
        $cmd
    fi  
    sleep 2  
done  
